### PR TITLE
Gem refactor

### PR DESCRIPTION
**Pull request by bsnape**
Nat,

I did a small refactor of the gem to follow conventions such as:
- removing the lockfile
- separating out runtime and development dependencies
- gem structure - a single entry point at `lib/yarjuf` which contains all internal and external dependencies

RSpec is now pessimistically versioned between `2.12` and `< 3.0` so we can make the next version of Yarjuf  (`1.0.6`?) the last that supports RSpec 2.

I've left updating the version to you or I can amend this PR before I refactor Yarjuf for RSpec 3 in a separate PR.

Ben

### CODE REVIEW

**Comment by bsnape** [comment]
Looks like there's a problem with one of `reek`'s dependencies `rainbow`.

https://github.com/sickill/rainbow/pull/18

Taking a look now.

**Comment by natritmeyer** [comment]
All looks good :)

There's one minor issue to do with the git history... and given you're the git master you can probably fix it. In this commit c75fe9bbe2f5f70c818a202f73be1866f8de8e23 can the moving of `lib/yarjuf.rb` to `lib/yarjuf/j_unit.rb` be represented as a git-move rather than a delete/new file?

**Comment by bsnape** [comment]
Current status: branch merge hell.

Trying to resolve...

**Comment by jhelwig** [comment]
@natritmeyer, Git doesn't explicitly track moves/copies/renames.  It detects them after the fact based on file similarity, so there isn't really anything to do.  `-M`, and `-C` can be used with log and diff to tell Git to detect renames & copies (using a default similarity score of 50%).  `git help diffcore` under the `DIFFCORE-RENAME` section has more details.

**Comment by bsnape** [comment]
@jhelwig it was my bad - in my original commit c75fe9b I moved the file (`lib/yarjuf.rb` to `lib/yarjuf/j_unit.rb`) _and_ modified its old path (`lib/yarjuf.rb`) in the same commit.

661f3a7 and 7640e07 fix that.

**Comment by natritmeyer** [comment]
Thanks :)

**Pull request merged**
